services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    restart: always
    ports:
      - published: 7000
        target: 7000
    networks:
      - api_network
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    networks:
      - api_network

networks:
  api_network:
    driver: bridge